services: 
  db: 
    image: mysql:8.0
    container_name: mysql8
    restart: unless-stopped
    env_file: .env
    ports: 
        - 3306:3306
    volumes: 
      - ./datas:/var/lib/mysql
      - ./entrypoint/01-user-init.sql:/docker-entrypoint-initdb.d/01-user-init.sql
      - ./entrypoint/02-recensement.sql:/docker-entrypoint-initdb.d/02-recensement.sql
      - ./entrypoint/03-group-rh.sql:/docker-entrypoint-initdb.d/03-group-rh.sql
    command: '--default-authentication-plugin=mysql_native_password'
  phpmyadmin: 
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
