services: 
  db: 
    image: mariadb:latest
    env_file: .env
    container_name: mariadb
    restart: unless-stopped
    ports: 
      - 3306:3306
    volumes: 
      - ./datas:/var/lib/mysql
      - ./entrypoint/01-user-init.sql:/docker-entrypoint-initdb.d/01-user-init.sql
      - ./entrypoint/02-recensement.sql:/docker-entrypoint-initdb.d/02-recensement.sql
      - ./entrypoint/03-group-rh.sql:/docker-entrypoint-initdb.d/03-group-rh.sql

  phpmyadmin: 
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1